### ISSUE TITLE
Convert JavaScript to Kotlin

### ISSUE THREAD

**Issue by BFergerson** [sourceplusplus/SourceMarker#251]
### Objective

Three pages need to be converted to Kotlinx.html, which are:
- [x] overview_view.js
- [x] traces_view.js
- [x] configuration_view.js
- [x] overview.js
- [x] traces.js
- [x] configuration.js
- [ ] source_eventbus_bridge.js

### Information
Save source_eventbus_bridge.js for last as it warrants further thinking and discussion.

**Comment by chess-equality** [comment]
@BFergerson In these snippets,

```javascript
   if (innerTraceStack.inner_level > 0) {
        $('#latest_traces_header_text').text('Parent Stack');
    } else {
```
```javascript
//todo: merge this method with displayTraceStack
function displayInnerTraces(innerTraceStack) { //todo-chess-equality: [innerTraceStack: List<TraceSpanInfo>]
```
https://github.com/sourceplusplus/SourceMarker/blob/master/portal/backend/src/main/resources/webroot/js/views/traces_view.js#L169-L171

https://github.com/sourceplusplus/SourceMarker/blob/master/portal/backend/src/main/resources/webroot/js/views/traces_view.js#L133-L134

`innerTraceStack` which is a `List<TraceSpanInfo>]` doesn't seem to have a property/function `innerLevel` (nor the js equivalent `inner_level`).

**Comment by chess-equality** [comment]
@BFergerson Do you mean then it will become `if (traceStack[0].innerLevel > 0)`?

> Feel free to ask me if you need a sensible default value.

Yes please I think I do. Thanks.

**Comment by BFergerson** [comment]
@chess-equality, `innerLevel: Int = 0` gives the type and the sensible default value. I meant for future fields.

**Comment by BFergerson** [comment]
@chess-equality, open a draft PR when you get a chance. We will merge in one converted page at a time.

**Comment by chess-equality** [comment]
@BFergerson Please see draft PR: https://github.com/sourceplusplus/SourceMarker/pull/261

**Comment by BFergerson** [comment]
@chess-equality, for the configuration page where it says the type is supposed to be `JsonObject` just go ahead and create the necessary object in the protocol module instead. Something like:
```kt
data class ArtifactInformation(
    val artifactQualifiedName: String,
    val createDate: Long,
    val lastUpdated: Long,
    val config: ArtifactConfiguration
)
data class ArtifactConfiguration(
    val endpoint: Boolean,
    val subscribeAutomatically: Boolean
    val endpointName: String,
    val endpointIds: List<Long>
)
```
