### ISSUE TITLE
sourcemarker portal is empty 

### ISSUE THREAD

**Issue by juhanishen** [sourceplusplus/SourceMarker#285]
![emptyPortal](https://user-images.githubusercontent.com/8583850/103871807-7d608d80-5108-11eb-973e-2036532cb7e9.png)

Hi, 

I have a standalone Java application in IntelliJ, now I have skywalking 8.0.1, I follow the guidance to type CTL+SHIFT+S, then I run the unit test to see how fast my java runs. But there is only empty visual Portal as shown in the picture.   Any idea I could make trouble shooting?

Juhani

**Comment by BFergerson** [comment]
There are a few issues I see here.

First, SourceMarker will not be able to show any metrics which are not picked up first by SkyWalking. When you run your application, are you able to view any metrics with the SkyWalking Rocketbot UI? If not, you won't see anything in SourceMarker either. If that's the case, I would make sure you're correctly attaching the SkyWalking agent and have the necessary plugins enabled. I would also like to mention that typically applications being monitored by SkyWalking are typically not unit tests. It's possible to monitor those as well but you would need to make sure that SkyWalking has finished receiving metric data before allowing the tests to finish and exit execution.

Second, the portal is showing up in dark mode, which it shouldn't. Can you share with me the theme you're using?

Finally, I agree having an empty portal is very confusing to new users. Would you agree that having a notification that states that SourceMarker was unable to find metric data from SkyWalking is a more appropriate solution?

**Comment by BFergerson** [comment]
Ran into an issue like this. Should be fixed with the next version.
